version: '3.8'
services:
  app:
    container_name: images
    image: ghcr.io/iamtakagi/images:latest
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./images:/app/static
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - PORT=3000
    ports:
      - 3000:3000